version: 1.0  
api_server:
  http:
    port: 5000
    cors:
      enabled: true
      access_control_allow_origins: ["*"]
      access_control_allow_methods: ["GET", "OPTIONS", "POST", "HEAD", "PUT"]
      access_control_allow_credentials: true
      access_control_allow_headers: ["*"]
      access_control_allow_origin_regex: 'https://.*\.my_org\.com'
      access_control_max_age: 1200
      access_control_expose_headers: ["Content-Length"]
  ssl:
    enabled: true