name: Build Bento
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'deployment.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python_version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build
        uses: bentoml/build-bento-action@main
        with:
          python_version: '3.11'
          build: 'true'
          action: skip
          deployment_name: zennoapi
          cloud_api_token: ${{ secrets.BENTOCLOUD_API_KEY }}
          cloud_endpoint: ${{ secrets.BENTOCLOUD_ENDPOINT }}